version: 2
deployment:
    staging:
        branch: master
        heroku:
            appname: home-restaurant

jobs:
   build:
     #working_directory: ~/home_restaurant
     docker:
       - image: circleci/node:4.8.2
     steps:
       - checkout
       - run: echo "hello world"